spring.application.name=tareas-domesticas

# 1. Conexión a PostgreSQL (localhost es tu PC)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_tareas_domesticas
spring.datasource.username=postgres
spring.datasource.password=rasengan17

# 2. Hibernate: Esta línea crea las tablas automáticamente en tu DB
spring.jpa.hibernate.ddl-auto=update

# 3. Muestra en la consola de IntelliJ las consultas que se hacen
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
